### ISSUE TITLE
Improve responsiveness of pages

### ISSUE THREAD

**Issue by JWGmeligMeyling** [devhub-tud/devhub#234]
Some tables aren't as responsive as could be
* Build servers overview: https://devhub.ewi.tudelft.nl/build-servers
* Table on assignment overview for groups:  https://devhub.ewi.tudelft.nl/courses/TI1706/groups/1/assignments
* Contributors overview for groups https://devhub.ewi.tudelft.nl/courses/TI1706/groups/1/contributors

Not sure how to fix this elegantly, but we could try:
```css
table {
  border: none;
}

table,
tr,
td,
tbody,
thead,
th {
  display: block;
}
```
